force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Track_Count__c.field-meta.xml
<CustomField>
    <fullName>Track_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Track Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/services/SongService.cls
public with sharing class SongService
{
    public static void updateSongFields(Set<Id> songIds)
    {
        List<AggregateResult> results = TrackSelector.countTracksOnSongs(songIds);

        List<Song__c> songsToUpdate = new List<Song__c>();

        for (AggregateResult res : results)
        {
            Id songId = (Id)res.get('songId');
            Integer trackCount = (Integer)res.get('trackCount');

            songsToUpdate.add(new Song__c(Id = songId, Track_Count__c = trackCount));
        }

        update songsToUpdate;
    }

    public static Set<Id> getIdsFromSongs(List<Song__c> songs)
    {
        Set<Id> songIds = new Set<Id>();

        for (Song__c song : songs)
        {
            songIds.add(song.Id);
        }

        return songIds;
    }
}