force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <label>Artist</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Song__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pop</fullName>
            </value>
            <value>
                <fullName>Hip Hop</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Rhythm and Blues</fullName>
            </value>
            <value>
                <fullName>Soul</fullName>
            </value>
            <value>
                <fullName>Reggae</fullName>
            </value>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>Folk</fullName>
            </value>
            <value>
                <fullName>Funk</fullName>
            </value>
            <value>
                <fullName>Middle Eastern</fullName>
            </value>
            <value>
                <fullName>Jazz</fullName>
            </value>
            <value>
                <fullName>Disco</fullName>
            </value>
            <value>
                <fullName>Classical</fullName>
            </value>
            <value>
                <fullName>Electronic</fullName>
            </value>
            <value>
                <fullName>Music of Latin America</fullName>
            </value>
            <value>
                <fullName>Music of Africa</fullName>
            </value>
            <value>
                <fullName>Music of Asia</fullName>
            </value>
            <value>
                <fullName>Traditional Music</fullName>
            </value>
            <value>
                <fullName>Independent Music</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Song__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Song__c/fields/Track_Count__c.field-meta.xml
<CustomField>
    <fullName>Track_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Track Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Song__c/fields/Track_Licenses__c.field-meta.xml
<CustomField>
    <fullName>Track_Licenses__c</fullName>
    <label>Track Licenses</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/selectors/SongSelector.cls
public with sharing class SongSelector extends fflib_SObjectSelector
{
    public List<Schema.SObjectField> getSObjectFieldList()
    {
        List<Schema.SObjectField> fieldsList = new List<Schema.SObjectField>();
        
        fieldsList.add(Song__c.Id);
        fieldsList.add(Song__c.Name);
        fieldsList.add(Song__c.Genre__c);
        fieldsList.add(Song__c.Length__c);
        fieldsList.add(Song__c.Artist__c);
        fieldsList.add(Song__c.Track_Count__c);
        fieldsList.add(Song__c.Track_Licenses__c);
        fieldsList.add(Song__c.Is_Active__c);

        return fieldsList;
    }

    public Schema.SObjectType getSObjectType()
    {
        return Song__c.SObjectType;
    }

    public static List<Song__c> selectById(Set<Id> ids)
    {
        SongSelector selector = new SongSelector();

        fflib_QueryFactory queryFactory = selector.newQueryFactory();
        return (List<Song__c>) Database.query(queryFactory.setCondition('Id IN :ids')
            .addOrdering(Consts.FIELD_NAME, fflib_QueryFactory.SortOrder.ASCENDING).toSOQL());
    }

    public static List<Song__c> selectByGenre(String genre, Integer offset)
    {
        SongSelector selector = new SongSelector();

        fflib_QueryFactory queryFactory = selector.newQueryFactory();

        if(genre != Consts.GENRE_ALL)
        {
            queryFactory.setCondition('Genre__c = :genre');
        }
        queryFactory.addOrdering(Consts.FIELD_NAME, fflib_QueryFactory.SortOrder.ASCENDING);
        queryFactory.setLimit(Consts.PAGINATION_BATCH_SIZE);
        queryFactory.setOffset(offset*Consts.PAGINATION_BATCH_SIZE);

        return (List<Song__c>) Database.query(queryFactory.toSOQL());
    }

    public static AggregateResult numberOfRecords(String genre)
    {
        String query = 'SELECT COUNT(Id) n FROM Song__c';

        if (genre != Consts.GENRE_ALL)
        {
            query += ' WHERE Genre__c = :genre';
        }

        return Database.query(query);
    }
}