force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pop</fullName>
            </value>
            <value>
                <fullName>Hip Hop</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Rhythm and Blues</fullName>
            </value>
            <value>
                <fullName>Soul</fullName>
            </value>
            <value>
                <fullName>Reggae</fullName>
            </value>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>Folk</fullName>
            </value>
            <value>
                <fullName>Funk</fullName>
            </value>
            <value>
                <fullName>Middle Eastern</fullName>
            </value>
            <value>
                <fullName>Jazz</fullName>
            </value>
            <value>
                <fullName>Disco</fullName>
            </value>
            <value>
                <fullName>Classical</fullName>
            </value>
            <value>
                <fullName>Electronic</fullName>
            </value>
            <value>
                <fullName>Music of Latin America</fullName>
            </value>
            <value>
                <fullName>Music of Africa</fullName>
            </value>
            <value>
                <fullName>Music of Asia</fullName>
            </value>
            <value>
                <fullName>Traditional Music</fullName>
            </value>
            <value>
                <fullName>Independent Music</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/trigger-handlers/SongTriggerHandler.cls
public with sharing class SongTriggerHandler extends TriggerHandlerBase
{
    protected override void onAfterUpdate()
    {
        handleGenreChange((Map<Id, Song__c>)Trigger.oldMap, (Map<Id, Song__c>)Trigger.newMap);
    }

    private void handleGenreChange(Map<Id, Song__c> oldMap, Map<Id, Song__c> newMap)
    {
        Set<Id> songsWithChangedGenreIds = new Set<Id>();

        for (Song__c newSong : newMap.values())
        {
            Song__c oldSong = oldMap.get(newSong.Id);

            if (newSong.Genre__c != oldSong.Genre__c)
            {
                songsWithChangedGenreIds.add(newSong.Id);
            }
        }

        if (songsWithChangedGenreIds.isEmpty())
        {
            return;
        }

        Set<Id> trackIds = TrackService.getTrackIdsFromSongs(songsWithChangedGenreIds);

        MixService.updateMixFields(trackIds);
    }
}