force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <label>Artist</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Song__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pop</fullName>
            </value>
            <value>
                <fullName>Hip Hop</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Rhythm and Blues</fullName>
            </value>
            <value>
                <fullName>Soul</fullName>
            </value>
            <value>
                <fullName>Reggae</fullName>
            </value>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>Folk</fullName>
            </value>
            <value>
                <fullName>Funk</fullName>
            </value>
            <value>
                <fullName>Middle Eastern</fullName>
            </value>
            <value>
                <fullName>Jazz</fullName>
            </value>
            <value>
                <fullName>Disco</fullName>
            </value>
            <value>
                <fullName>Classical</fullName>
            </value>
            <value>
                <fullName>Electronic</fullName>
            </value>
            <value>
                <fullName>Music of Latin America</fullName>
            </value>
            <value>
                <fullName>Music of Africa</fullName>
            </value>
            <value>
                <fullName>Music of Asia</fullName>
            </value>
            <value>
                <fullName>Traditional Music</fullName>
            </value>
            <value>
                <fullName>Independent Music</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Song__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Song__c/fields/Track_Count__c.field-meta.xml
<CustomField>
    <fullName>Track_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Track Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Song__c/fields/Track_Licenses__c.field-meta.xml
<CustomField>
    <fullName>Track_Licenses__c</fullName>
    <label>Track Licenses</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/tests/SongSelectorTest.cls
@isTest
private class SongSelectorTest
{
    @TestSetup
    static void makeData()
    {
        List<Song__c> songs = new List<Song__c>();

        for(Integer i = 0; i < 200; i++)
        {
            Song__c song = new Song__c();
            song.Name = 'Test' + i;
            song.Length__c = 180;
            song.Artist__c = 'Test Artist' + i;
            song.Track_Count__c = 0;
            song.Track_Licenses__c = 10;

            if(i < 100)
            {
                song.Genre__c = 'Rock';
            }
            else
            {
                song.Genre__c = 'Pop';
            }

            songs.add(song);
        }

        insert songs;
    }

    @isTest
    static void selectById()
    {
        List<Song__c> songs = [SELECT Id FROM Song__c LIMIT 50];

        Set<Id> songIds = Utils.getIdFieldValue(songs, 'Id');

        Test.startTest();
        List<Song__c> selectedSongs = SongSelector.selectById(songIds);
        Test.stopTest();

        System.assertEquals(50, selectedSongs.size());
    }

    @isTest
    static void selectByGenre()
    {
        Test.startTest();
        List<Song__c> songs = SongSelector.selectByGenre('Rock', 0);
        Test.stopTest();

        if(Consts.PAGINATION_BATCH_SIZE < 100)
        {
            System.assertEquals(Consts.PAGINATION_BATCH_SIZE, songs.size());
        }
        else
        {
            System.assertEquals(100, songs.size());
        }

        for(Song__c song : songs)
        {
            System.assertEquals('Rock', song.Genre__c);
        }
    }

    @isTest
    static void numberOfRecords()
    {
        Test.startTest();
        AggregateResult result = SongSelector.numberOfRecords('Rock');
        Test.stopTest();

        System.debug(result);

        Integer numberOfRecords = (Integer) result.get('n');

        System.assertEquals(100, numberOfRecords);
    }
}