force-app/main/default/objects/Mix__c/Mix__c.object-meta.xml
<CustomObject>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Mix__c.field-meta.xml
<CustomField>
    <fullName>Mix__c</fullName>
    <label>Mix</label>
    <referenceTo>Mix__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/trigger-handlers/TrackTriggerHandler.cls
public with sharing class TrackTriggerHandler extends TriggerHandlerBase
{
    protected override void onBeforeInsert()
    {
        checkIfMaxTrackAmountPerMixWasHit();
    }

    protected override void onBeforeUpdate()
    {
        checkIfMaxTrackAmountPerMixWasHit();
    }

    protected override void onAfterInsert()
    {
        
    }

    protected override void onAfterUpdate()
    {
        
    }

    protected override void onAfterDelete()
    {
        
    }

    protected override void onAfterUnDelete()
    {
        checkIfMaxTrackAmountPerMixWasHit();
    }

    private void checkIfMaxTrackAmountPerMixWasHit()
    {
        TrackService.processAddedTracks((List<Track__c>)Trigger.new);
    }

    private void handleMixUpdates(Map<Id, Track__c> oldMap, Map<Id, Track__c> newMap)
    {
        Set<Id> updatedMixIds = new Set<Id>();
        
        for (Track__c newTrack : newMap.values())
        {
            Track__c oldTrack = oldMap.get(newTrack.Id);

            if (newTrack.Mix__c != oldTrack.Mix__c)
            {
                if (newTrack.Mix__c != null)
                {
                    updatedMixIds.add(newTrack.Mix__c);
                }

                if (oldTrack.Mix__c != null)
                {
                    updatedMixIds.add(oldTrack.Mix__c);
                }
            }
        }

        MixService.updateMixFields(updatedMixIds);
    }
}