force-app/main/default/objects/Mix__c/Mix__c.object-meta.xml
<CustomObject>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Mix__c.field-meta.xml
<CustomField>
    <fullName>Mix__c</fullName>
    <label>Mix</label>
    <referenceTo>Mix__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/selectors/MixSelector.cls
public with sharing class MixSelector
{
    public static Set<Id> selectFullMixIds(Set<Id> mixIds)
    {
        //found no way to implement this in fflib
        List<AggregateResult> queryRes = [SELECT Mix__c FROM Track__c GROUP BY Mix__c HAVING COUNT(Id) > :Consts.MAX_TRACKS_PER_MIX AND Mix__c IN :mixIds];
        
        Set<Id> fullMixesIds = new Set<Id>();

        for (AggregateResult res : queryRes)
        {
            fullMixesIds.add((Id)res.get('Mix__c'));
        }

        return fullMixesIds;
    }
}