force-app/main/default/objects/Mix__c/Mix__c.object-meta.xml
<CustomObject>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Mix__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mixes</relationshipLabel>
    <relationshipName>Mixes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pop</fullName>
            </value>
            <value>
                <fullName>Hip Hop</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Rhythm and Blues</fullName>
            </value>
            <value>
                <fullName>Soul</fullName>
            </value>
            <value>
                <fullName>Reggae</fullName>
            </value>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>Folk</fullName>
            </value>
            <value>
                <fullName>Funk</fullName>
            </value>
            <value>
                <fullName>Middle Eastern</fullName>
            </value>
            <value>
                <fullName>Jazz</fullName>
            </value>
            <value>
                <fullName>Disco</fullName>
            </value>
            <value>
                <fullName>Classical</fullName>
            </value>
            <value>
                <fullName>Electronic</fullName>
            </value>
            <value>
                <fullName>Music of Latin America</fullName>
            </value>
            <value>
                <fullName>Music of Africa</fullName>
            </value>
            <value>
                <fullName>Music of Asia</fullName>
            </value>
            <value>
                <fullName>Traditional Music</fullName>
            </value>
            <value>
                <fullName>Independent Music</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Mix__c.field-meta.xml
<CustomField>
    <fullName>Mix__c</fullName>
    <label>Mix</label>
    <referenceTo>Mix__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Track__c/fields/Song__c.field-meta.xml
<CustomField>
    <fullName>Song__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Song</label>
    <referenceTo>Song__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/controllers/MixBuilderController.cls
public with sharing class MixBuilderController
{
    @AuraEnabled(cacheable=true)
    public static String getMix(String mixId)
    {
        Mix__c selectedMix = MixSelector.selectById(new Set<Id>{(Id)mixId})[0];

        Set<Id> selectedSongIds = Utils.getIdFieldValue(
            TrackSelector.selectByMixId(new Set<Id>{(Id)mixId}), Consts.FIELD_SONG);

        MixWrapper wrapper = new MixWrapper(
            selectedMix.Id, selectedMix.Name, selectedMix.Customer__c,
            SongSelector.selectById(selectedSongIds)
        );

        return JSON.serialize(wrapper);
    }

    @AuraEnabled(cacheable=false)
    public static void handleMixUpsert(String mixJson)
    {
        MixWrapper mix = (MixWrapper)JSON.deserialize(mixJson, MixWrapper.class);
        
        if (mix.mixId == null)
        {
            MixService.createNewMix(mix);
        }
        else
        {
            MixService.updateExistingMix(mix);
        }
    }

    @AuraEnabled(cacheable=false)
    public static void handleVinylProduce(String mixJson)
    {
        VinylWrapper vinyl = (VinylWrapper)JSON.deserialize(mixJson, VinylWrapper.class);

        Id mixId = vinyl.mixId;

        Map<Id, Integer> songIds = new Map<Id, Integer>();
        for (Track__c song : vinyl.selectedTracks)
        {
            songIds.put(song.Id, (Integer)song.Index__c);
        }

        List<Track__c> tracks = TrackSelector.selectByMixId(new Set<Id>{mixId});

        for (Track__c track : tracks)
        {
            track.Index__c = songIds.get(track.Song__c);
        }

        update tracks;
    }

    @AuraEnabled(cacheable=true)
    public static List<Song__c> getSongsByIds(List<Id> musicList)
    {
        return SongSelector.selectById(new Set<Id>(musicList));
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getGenres()
    {
        List<String> genres = new List<String>();
        List<Schema.PicklistEntry> picklistEntries = Song__c.Genre__c.getDescribe().getPicklistValues();
        
        for (Schema.PicklistEntry entry : picklistEntries) {
            genres.add(entry.getLabel());
        }
        
        return genres;
    }

    @AuraEnabled(cacheable=true)
    public static List<Song__c> getSongsByGenre(String genre, Integer offset)
    {
        return SongSelector.selectByGenre(genre, offset);
    }

    @AuraEnabled(cacheable=true)
    public static Integer getPages(String genre)
    {
        Integer numberOfRecords = (Integer)SongSelector.numberOfRecords(genre).get('n');
        return numberOfRecords/Consts.PAGINATION_BATCH_SIZE + 1;
    }

    @AuraEnabled(cacheable=true)
    public static List<Map<String, Object>> getTrackOrder(String mixId)
    {
        List<Track__c> tracks = TrackSelector.selectByMixId(new Set<Id>{(Id)mixId});
        
        List<Map<String, Object>> songIds = new List<Map<String, Object>>();

        for (Track__c track : tracks)
        {
            Map<String, Object> songMap = new Map<String, Object>();
            songMap.put(Consts.FIELD_ID, track.Song__c);
            songMap.put(Consts.FIELD_INDEX, track.Index__c);
            songIds.add(songMap);
        }

        return songIds;
    }

    @AuraEnabled
    public static void sendEmailWithPdf(String contactId, String pdfBase64, String fileName)
    {
        List<Contact> contacts = ContactSelector.selectById(new Set<Id>{(Id)contactId});
        
        EmailManager.sendEmailWithPdf(contacts, pdfBase64, fileName);
    }
}