force-app/main/default/objects/Mix__c/Mix__c.object-meta.xml
<CustomObject>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Mix__c.field-meta.xml
<CustomField>
    <fullName>Mix__c</fullName>
    <label>Mix</label>
    <referenceTo>Mix__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/services/TrackService.cls
public with sharing class TrackService
{
    public static void processAddedTracks(List<Track__c> newTracks)
    {
        Set<Id> mixIds = new Set<Id>();
        for (Track__c track : newTracks)
        {
            mixIds.add(track.Mix__c);
        }

        Set<Id> fullMixesIds = MixSelector.selectFullMixIds(mixIds);

        if (fullMixesIds.isEmpty())
        {
            return;
        }

        for(Track__c track : newTracks)
        {
            if (fullMixesIds.contains(track.Mix__c))
            {
                track.addError('Max amount of tracks per mix reached');
            }
        }
    }

    public static Set<Id> getMixIdsFromTracks(Set<Id> trackIds)
    {
        List<Track__c> tracks = [
            SELECT Mix__c
            FROM Track__c
            WHERE Id IN :trackIds];

        Set<Id> mixIds = new Set<Id>();

        for (Track__c track : tracks)
        {
            if(track.Mix__c != null)
            {
                mixIds.add(track.Mix__c);
            }
        }

        return mixIds;
    }
}