force-app/main/default/objects/Mix__c/Mix__c.object-meta.xml
<CustomObject>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Mix__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mixes</relationshipLabel>
    <relationshipName>Mixes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mix__c/fields/Primary_Genre__c.field-meta.xml
<CustomField>
    <fullName>Primary_Genre__c</fullName>
    <label>Primary Genre</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mix__c/fields/Secondary_Genre__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Genre__c</fullName>
    <label>Secondary Genre</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <label>Artist</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Song__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pop</fullName>
            </value>
            <value>
                <fullName>Hip Hop</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Rhythm and Blues</fullName>
            </value>
            <value>
                <fullName>Soul</fullName>
            </value>
            <value>
                <fullName>Reggae</fullName>
            </value>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>Folk</fullName>
            </value>
            <value>
                <fullName>Funk</fullName>
            </value>
            <value>
                <fullName>Middle Eastern</fullName>
            </value>
            <value>
                <fullName>Jazz</fullName>
            </value>
            <value>
                <fullName>Disco</fullName>
            </value>
            <value>
                <fullName>Classical</fullName>
            </value>
            <value>
                <fullName>Electronic</fullName>
            </value>
            <value>
                <fullName>Music of Latin America</fullName>
            </value>
            <value>
                <fullName>Music of Africa</fullName>
            </value>
            <value>
                <fullName>Music of Asia</fullName>
            </value>
            <value>
                <fullName>Traditional Music</fullName>
            </value>
            <value>
                <fullName>Independent Music</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Song__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Song__c/fields/Track_Count__c.field-meta.xml
<CustomField>
    <fullName>Track_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Track Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Song__c/fields/Track_Licenses__c.field-meta.xml
<CustomField>
    <fullName>Track_Licenses__c</fullName>
    <label>Track Licenses</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Mix__c.field-meta.xml
<CustomField>
    <fullName>Mix__c</fullName>
    <label>Mix</label>
    <referenceTo>Mix__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Track__c/fields/Song__c.field-meta.xml
<CustomField>
    <fullName>Song__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Song</label>
    <referenceTo>Song__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/tests/MixServiceTest.cls
@isTest
public with sharing class MixServiceTest
{
    @TestSetup
    static void makeData()
    {
        TestHelper.insertTestMixes();
    }

    @isTest
    static void getMixGenreCountMap()
    {
        Set<Id> mixIds = new Set<Id>();

        List<Mix__c> mixes = [SELECT Id FROM Mix__c LIMIT 3];

        for(Mix__c mix : mixes)
        {
            mixIds.add(mix.Id);
        }

        Map<Id, Map<String, Integer>> mixGenreCount = MixService.getMixGenreCountMap(mixIds);

        System.assertEquals(3, mixGenreCount.size());

        for(Mix__c mix : mixes)
        {
            System.assertEquals(10, mixGenreCount.get(mix.Id).get(TestHelper.GENRE_ROCK));
        }
    }

    @isTest
    static void updateMixFields()
    {
        List<Mix__c> mixes = [SELECT Id FROM Mix__c LIMIT 3];

        Set<Id> mixIds = Utils.getIdFieldValue(mixes, Consts.FIELD_ID);

        Test.startTest();
        MixService.updateMixFields(mixIds);
        Test.stopTest();

        List<Mix__c> updatedMixes = [SELECT Id, Primary_Genre__c, Secondary_Genre__c FROM Mix__c LIMIT 3];

        for(Mix__c mix : updatedMixes)
        {
            System.assertEquals(TestHelper.GENRE_ROCK, mix.Primary_Genre__c);
            System.assertEquals(null, mix.Secondary_Genre__c);
        }
    }

    @isTest
    static void getFullMixIdsNoFullMixes()
    {
        List<Mix__c> mixes = [SELECT Id FROM Mix__c LIMIT 3];

        Set<Id> mixIds = Utils.getIdFieldValue(mixes, Consts.FIELD_ID);

        Set<Id> fullMixIds = MixService.getFullMixIds(mixIds);

        System.assertEquals(0, fullMixIds.size());
    }

    @isTest
    static void getFullMixIds()
    {
        List<Mix__c> mixes = [SELECT Id FROM Mix__c LIMIT 3];

        Set<Id> mixIds = Utils.getIdFieldValue(mixes, Consts.FIELD_ID);

        Mix__c fullMix = new Mix__c(Name = 'Full Mix');
        insert fullMix;

        List<Track__c> tracksToAdd = new List<Track__c>();

        List<Song__c> songs = [SELECT Id FROM Song__c LIMIT 20];

        for(Integer i = 0; i < 20; i++)
        {
            Track__c track = new Track__c();
            track.Mix__c = fullMix.Id;
            track.Song__c = songs[i].Id;

            tracksToAdd.add(track);
        }

        insert tracksToAdd;

        mixIds.add(fullMix.Id);

        Test.startTest();
        Set<Id> fullMixIds = MixService.getFullMixIds(mixIds);
        Test.stopTest();

        System.assertEquals(1, fullMixIds.size());
        System.assertEquals(fullMix.Id, fullMixIds.iterator().next());
    }

    @isTest
    static void createNewMix()
    {
        List<Mix__c> mixes = [SELECT Id FROM Mix__c];

        delete mixes;

        List<Song__c> songs = new List<Song__c>();

        for(Integer i = 0; i < 20; i++)
        {
            Song__c song = new Song__c();
            song.Name = 'Test' + i;
            song.Length__c = 180;
            song.Artist__c = 'Test Artist' + i;
            song.Track_Count__c = 0;
            song.Track_Licenses__c = 10;

            if(i < 15) 
            {
                song.Genre__c = TestHelper.GENRE_ROCK;
            }
            else
            {
                song.Genre__c = TestHelper.GENRE_POP;
            }

            songs.add(song);
        }

        insert songs;

        MixWrapper mix = new MixWrapper(null, 'New Mix', null, songs);

        Test.startTest();
        MixService.createNewMix(mix);
        Test.stopTest();

        mixes = [SELECT Id, Name, Customer__c, Primary_Genre__c, Secondary_Genre__c FROM Mix__c];

        System.assertEquals(1, mixes.size());
        System.assertEquals('New Mix', mixes[0].Name);
        System.assertEquals(TestHelper.GENRE_ROCK, mixes[0].Primary_Genre__c);
        System.assertEquals(TestHelper.GENRE_POP, mixes[0].Secondary_Genre__c);
    }

    @isTest
    static void updateExistingMixMoreSongs()
    {
        Mix__c mixToUpdate = [SELECT Id FROM Mix__c LIMIT 1];

        List<Song__c> songs = [SELECT Id FROM Song__c LIMIT 20];

        MixWrapper mixWrapper = new MixWrapper(mixToUpdate.Id, 'Updated Mix', null, songs);

        Test.startTest();
        MixService.updateExistingMix(mixWrapper);
        Test.stopTest();

        Mix__c mix = [SELECT Id, Name FROM Mix__c WHERE Id = :mixToUpdate.Id];

        System.assertEquals('Updated Mix', mix.Name);
        System.assertEquals(20, [SELECT count() FROM Track__c WHERE Mix__c = :mix.Id]);
    }

    @isTest
    static void updateExistingMixLessSongs()
    {
        Mix__c mixToUpdate = [SELECT Id FROM Mix__c LIMIT 1];

        List<Song__c> songs = [SELECT Id FROM Song__c LIMIT 5];

        MixWrapper mixWrapper = new MixWrapper(mixToUpdate.Id, 'Updated Mix', null, songs);

        Test.startTest();
        MixService.updateExistingMix(mixWrapper);
        Test.stopTest();

        Mix__c mix = [SELECT Id, Name FROM Mix__c WHERE Id = :mixToUpdate.Id];

        System.assertEquals('Updated Mix', mix.Name);
        System.assertEquals(5, [SELECT count() FROM Track__c WHERE Mix__c = :mix.Id]);
    }
}