force-app/main/default/objects/Mix__c/Mix__c.object-meta.xml
<CustomObject>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Mix__c/fields/Primary_Genre__c.field-meta.xml
<CustomField>
    <fullName>Primary_Genre__c</fullName>
    <label>Primary Genre</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mix__c/fields/Secondary_Genre__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Genre__c</fullName>
    <label>Secondary Genre</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Mix__c.field-meta.xml
<CustomField>
    <fullName>Mix__c</fullName>
    <label>Mix</label>
    <referenceTo>Mix__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Track__c/fields/Song__c.field-meta.xml
<CustomField>
    <fullName>Song__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Song</label>
    <referenceTo>Song__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/tests/TrackTriggerTest.cls
@isTest
public with sharing class TrackTriggerTest 
{
    @TestSetup
    static void makeData(){
        TestHelper.insertTestMixes();
    }

    @isTest
    static void testInsertTooManyTracks()
    {
        Mix__c mix = [SELECT Id FROM Mix__c LIMIT 1];

        List<Track__c> tracks = new List<Track__c>();
        for(Integer i = 0; i < 11; i++)
        {
            Track__c track = new Track__c();
            track.Mix__c = mix.Id;
            track.Song__c = null;
            track.Index__c = i;

            tracks.add(track);
        }

        Boolean caughtException = false;

        Test.startTest();
        try {
            insert tracks;
        } catch (DmlException e) {
            caughtException = true;
        }
        Test.stopTest();

        System.assertEquals(true, caughtException);
    }

    @isTest
    static void testUpdateSongOnTrack()
    {
        List<Track__c> tracks = [SELECT Id, Song__c FROM Track__c];
        for(Track__c track : tracks)
        {
            track.Song__c = null;
        }

        Test.startTest();
        update tracks;
        Test.stopTest();

        List<Mix__c> mixes = [SELECT Id, Primary_Genre__c, Secondary_Genre__c FROM Mix__c];

        for(Mix__c mix : mixes)
        {
            System.assertEquals(null, mix.Primary_Genre__c);
            System.assertEquals(null, mix.Secondary_Genre__c);
        }
    }

    @isTest
    static void testDeleteTracks()
    {
        List<Track__c> tracks = [SELECT Id FROM Track__c];

        Test.startTest();
        delete tracks;
        Test.stopTest();

        List<Mix__c> mixes = [SELECT Id, Primary_Genre__c, Secondary_Genre__c FROM Mix__c];

        for(Mix__c mix : mixes)
        {
            System.assertEquals(null, mix.Primary_Genre__c);
            System.assertEquals(null, mix.Secondary_Genre__c);
        }
    }

    @isTest
    static void testUndeleteTracks()
    {
        List<Track__c> tracks = [SELECT Id FROM Track__c];

        delete tracks;

        Test.startTest();
        undelete tracks;
        Test.stopTest();

        List<Mix__c> mixes = [SELECT Id, Primary_Genre__c, Secondary_Genre__c FROM Mix__c];

        for(Mix__c mix : mixes)
        {
            System.assertEquals(TestHelper.GENRE_ROCK, mix.Primary_Genre__c);
            System.assertEquals(null, mix.Secondary_Genre__c);
        }
    }
}