force-app/main/default/objects/Mix__c/Mix__c.object-meta.xml
<CustomObject>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Mix__c.field-meta.xml
<CustomField>
    <fullName>Mix__c</fullName>
    <label>Mix</label>
    <referenceTo>Mix__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/trigger-handlers/MixTriggerHandler.cls
public with sharing class MixTriggerHandler extends TriggerHandlerBase
{
    protected override void onBeforeDelete()
    {
        deleteTracks((List<Mix__c>)Trigger.old);
    }

    private static void deleteTracks(List<Mix__c> mixes)
    {
        Set<Id> mixIds = Utils.getIdFieldValue(mixes, Consts.FIELD_ID);
        List<Track__c> tracks = TrackSelector.selectByMixId(mixIds);

        delete tracks;
    }
}